import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.min.css';
import Navbar from "react-bootstrap/Navbar";
import Container from "react-bootstrap/Container";
import Nav from "react-bootstrap/Nav";
import Head from "next/head";
import Image from "next/image";
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }) {
  return (
    <>
     <Head>
        <title>Sign Language Translation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Navbar bg="dark" variant="dark">
    <Container>
      <Navbar.Brand href="/">SIGN LANGUAGE TRANSLATION</Navbar.Brand>
      <Nav className="me-auto">
        <Nav.Link href="/translate">Translation</Nav.Link>
        <Nav.Link href="/gesture">Add Gesture</Nav.Link>
      </Nav>
    </Container>
  </Navbar>
  <Component {...pageProps} />
  </>
  )
}

export default MyApp
